### ISSUE TITLE
✅ [23.03.15] About 페이지 제작

### ISSUE THREAD

**Issue by jangjihoon96** [likelion4th-React-LAB15/final-project#11]
## Todo
- [x] About 페이지안 컴포넌트 구성
- [x] Style components를 활용하여 스타일링
- [x] 스크롤 트리거를 활용하여 인터렉션 구현
