### ISSUE TITLE
✅ [23.03.18] Reservation1,2 페이지 기능 구현

### ISSUE THREAD

**Issue by jenny7732** [likelion4th-React-LAB15/final-project#15]
## Todo
- [x] 상단 프로그래스바 완성
- [x] px 단위에서 rem 단위 변경
- [x] `Reservation1` 과 `Reservation2` 페이지 연결
