### ISSUE TITLE
✅ [23.03.20] Guam 페이지 완성

### ISSUE THREAD

**Issue by jangjihoon96** [likelion4th-React-LAB15/final-project#24]
## Todo
- [x] Guam 컴포넌트 제작 (Saipan 페이지에서 재사용 가능하도록)
- [x] gsap 스크롤 트리거 효과 적용
- [x] 스와이퍼 제작 (접근성 고려)
