### ISSUE TITLE
✅ [23.03.22] Saipan 페이지 제작

### ISSUE THREAD

**Issue by jangjihoon96** [likelion4th-React-LAB15/final-project#25]
## Todo
- [x] 기존에 만들어놓은 컴포넌트 활용하여 페이지 구성
- [x] 들어가는 데이터 내용 Saipan 관련하여 변경
- [x] 필요한 이미지 추가(이미지 최적화)
