### ISSUE TITLE
✅ [23.04.18] 메인페이지 메뉴버튼 키보드 접근성 및 이미지 대체텍스트 추가, 비디오 명도대비 조율

### ISSUE THREAD

**Issue by ovelute53** [likelion4th-React-LAB15/final-project#50]
## Todo
- [x] 메인페이지 메뉴 버튼 키보드 접근성
- [x] 이미지 대체 텍스트 자세하게 작성
- [x] 메인페이지 자동재생 비디오 명도대비 조율
