### ISSUE TITLE
✅ [23.04.18] 메인페이지 및 괌,사이판 페이지 리팩토링

### ISSUE THREAD

**Issue by jangjihoon96** [likelion4th-React-LAB15/final-project#51]
## Todo
- [x] 메인페이지 메인섹션 배경변화시 텍스트 및 버튼 안보이는 이슈 해결
- [x] 메인페이지 FilmList a11y-hidden 내용 수정
- [x] 괌,사이판 페이지 지도 이미지 대체 텍스트 수정
- [x] 괌,사이판 페이지 테이블 행열 구분 (scope 사용)
