### ISSUE TITLE
✅ [23.03.13] 메인 페이지 컴포넌트 제작 및 인터렉션 적용

### ISSUE THREAD

**Issue by jangjihoon96** [likelion4th-React-LAB15/final-project#6]
## Todo
- [x] headerMenu 인터렉션 구현
- [x] header 컴포넌트 완성
- [x] Visual 텍스트 인터랙션 완성
- [x] Visual 예약 컴포넌트 완성
- [x] mainSection1 컴포넌트 완성
- [x] footer 컴포넌트 완성
- [x] Wave 컴포넌트 완성
- [x] FilmList 컴포넌트 완성
- [x] FimList 애니메이션 구현
- [x] Siheky 컴포넌트 완성
- [x] Siheky 스크롤트리거 기능 구현
